### ISSUE TITLE
Dockerize!

### ISSUE THREAD

**Issue by Blizzara** [teekkarispeksi/nappikauppa2#101]
Setup Dockerfile to run this thing inside a container. Possibly separate versions for dev and prod uses. Prod should preferably contain only the compiled sources and packages needed to run the system (i.e., the same as what 'build_tar.sh' currently does).

Check that logs are still persisted somewhere out of the container.

Check that container exits with error if node dies for any reason, to allow auto-restart after failure.

**Comment by OpaL2** [comment]
Create gulp task for compiling and minifying sources and building docker image, so we can remove all strange shell scripts.

**Comment by OpaL2** [comment]
Done in PR #148
