### ISSUE TITLE
Mailirunko alennuskoodien lähetyksessä

### ISSUE THREAD

**Issue by NorthernCode** [teekkarispeksi/nappikauppa2#103]
Lähtevän sähköpostin rungoksi ei päädy se mitä tekstikentässä lukee. 

" toi sähköpostin runko ei näköjään muokkaannu sen mukaan mitä tuohon laatikkoon kirjottaa, tulee aina default siihen mailiin"

"näköjään joo pitää eka muuttaa sitä viestii ja sit vast generoida koodit, sillon pitäs toimii"

**Comment by OpaL2** [comment]
Fixed in commit d8606ad017ebfc80cd0347f7a2690c37ee746411
