### ISSUE TITLE
Change "Haluan tiedon ensi vuoden lipunmyynnistä" to "Haluan liittyä tiedotuslistalle"

### ISSUE THREAD

**Issue by Blizzara** [teekkarispeksi/nappikauppa2#123]
Or something. The point is, a) remove the limitation from our end to send only a single email (many of our customers might want to be customers also two years from now), and b) allow users to manage their membership themselves.

so,
1) opt-in checkbox to join the list, with rules of the list explained (i.e., a) will only send emails related to Teekkarispeksi's events and events where we are selling tickets to (to allow for Nääspeksi or similar) b) at most x (4?) emails per year c) can leave list any time

2) create the list somewhere and automatically add opt-in'ed ppl

3) deprecate the column from sql schema

**Comment by OpaL2** [comment]
So, we need email mailing service which has API for adding and removing participants.

## Major required features:

* Customer subscribes to mailing list via API from nappikauppa2 or other source.
* Email can be send through list easily using authenticated SMTP
* Sort tag gets automatically added to title of email
* Each email includes footer with unsubscribe link and Privacy policy link.
* API must have strong authentication with tokens or some other means.

**Comment by OpaL2** [comment]
With quick lookup [mailguns mailing list](https://documentation.mailgun.com/en/latest/api-mailinglists.html) should satisfy requirements from technicat perspective.

**Comment by Blizzara** [comment]
Yep, Mailgun lists look like a good option here. We don't need to store any other info there though - just the subscription (ie. email address). Mailgun seems to suggest storing also timestamp and possibly IP address as a proof of consent, I'm not sure if that is really needed.
