### ISSUE TITLE
Write privacy policy 

### ISSUE THREAD

**Issue by Blizzara** [teekkarispeksi/nappikauppa2#125]

**Comment by OpaL2** [comment]
Under progress, but in my opinion will be hosted on different service and only linked to nappikauppa2

**Comment by Blizzara** [comment]
I'm fine with anything, but why?

**Comment by OpaL2** [comment]
Privacy policy can be found from [rekisterit.teekkarispeksi.fi/lippukauppa](rekisterit.teekkarispeksi.fi/lippukauppa) where all other privacy policies for teekkarispeksi ry can be found.

**Comment by Blizzara** [comment]
@OpaL2 Do we have the link? If not, I'd reopen this to add it.
