### ISSUE TITLE
Support Checkout in addition to Paytrail for payments

### ISSUE THREAD

**Issue by Blizzara** [teekkarispeksi/nappikauppa2#98]
We want to move away from Paytrail as [Checkout](https://checkout.fi/) seems like a cheaper alternative. Currently Paytrail is baked into https://github.com/teekkarispeksi/nappikauppa2/blob/master/backend/src/order.ts

To fix: abstract payment logic into it's own interface and create Paytrail and Checkout classes that implement the payment handling.

Checkout API description: https://checkoutfinland.github.io/#introduction

**Comment by OpaL2** [comment]
#133
